version: "3"

services: 
  app:
      build: .
      environment:
        HOST: db
        EXPRESS_PORT: 4001
        DATABASE: mef
        PWD_SECRET: contrasenasupersecreta
        DATABASE_PORT: db
        DATABASE_TYPE: postgres
        DATABASE_USER: postgres
        DATABASE_PASSWORD: postgres
        NODE_ENV: development
        SESS_LIFETIME: 1000*60*60*2
        SESS_NAME: sid
        SESS_SECRET: ssh!qiert,it\'asecret!
      volumes: 
        - ".:/usr/src"
        - "/usr/src/node_modules"
      restart: always
      ports: 
          - 4001:4001
      depends_on:
        - db
        - sphinx
      networks:
      - mefnetwork

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mef
    ports: 
      - '5432:5432'
    restart: always
    depends_on:
      - sphinx
    volumes:
      - /mefdata
    networks:
      - mefnetwork

  sphinx:
    image: sphinxdoc/sphinx
    volumes:
      - "./docs:/docs"
      - ./public/docs:/public/docs
    command: "sphinx-build -b html /docs /public/docs"
    restart: always

networks:
  mefnetwork:
    driver: "bridge"
volumes:
  node_modules: